import type { Metadata } from "next";
import { IBM_Plex_Sans_Arabic } from "next/font/google";
import "./globals.css";
import PrelineScriptWrapper from "../components/PrelineScriptWrapper";
import { getGlobalData } from "@/data/loader";
import Navbar from "@/components/ui/Navbar";

const ibmPlexSansArabic = IBM_Plex_Sans_Arabic({
  weight: ["400", "500", "600", "700"],
  subsets: ["arabic"],
  variable: "--font-ibm-plex-arabic",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const globalData = await getGlobalData();
  console.log("golabalData===", globalData);

  return (
    <html lang="ar" dir="rtl">
      <body className={`${ibmPlexSansArabic.className} antialiased`}>
        <Navbar data={globalData.header} />
        <div>{children}</div>
        <PrelineScriptWrapper />
      </body>
    </html>
  );
}
